### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by Ken-Nakayama** [Ken-Nakayama/furima-39754#23]
# URL
https://furima-39754.onrender.com/

# Basic認証ID&パスワード
・ID：admin
・パスワード：2222

# 出品者情報
・名前：出品者
・メールアドレス：syuppin@email.com
・パスワード：123abc

# 購入者情報
・名前：購入者
・メールアドレス：kounyu@email.com
・パスワード：123abc

**Comment by mo1015** [comment]
@Ken-Nakayama さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]

- [x] **新規登録・ログイン共にエラーハンドリングができていること（入力に問題がある状態で「会員登録」または「ログイン」ボタンが押された場合、情報は受け入れられず、各ページでエラーメッセージが表示されることを確認）**
新規登録ページでエラーメッセージが表示されません。

- [x] **入力された販売価格によって、販売手数料や販売利益が変わること(JavaScriptを使用して実装すること)**
一度出品に失敗しエラーが出た後に再度価格を入力すると、販売手数料と販売利益が表示されなくなってしまいます。どの段階でも入力したら表示されるよう修正しましょう。

- [x] **エラーハンドリングができていること
（入力に問題がある状態で「出品する」ボタンが押された場合、情報は保存されず、出品ページに戻りエラーメッセージが表示されること）**
全ての入力に問題がある状態で「出品する」ボタンを押しても、エラーメッセージが「Image を選択してください
」しか表示されません。

- [x]  **商品出品時に登録した情報（商品名・商品画像・販売価格・配送料負担・商品説明・出品者名・カテゴリー・商品の状態・発送元の地域・発送日の目安・○○をもっと見る）が、見本アプリと同様の形で出力されること**
出品者名が、本人情報のお名前で表示されています。ニックネームが表示されるよう修正しましょう。

修正が完了しましたら、一度ご自身の本番環境で正しく動作しているか確認してみましょう！
修正内容が反映されていることを確認できましたら以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by Ken-Nakayama** [comment]
# What
・ユーザー新規登録ページでのエラーメッセージの表示。
・商品手数料等計算用javascriptのrender時読み込み機能の追加。
・商品出品ページでのエラーメッセージの表示修正。
・商品詳細ページでのニックネーム表示。
・プルリクエスト（下記のとおり）
https://github.com/Ken-Nakayama/furima-39754/pull/24

# Why
・フリマアプリ挙動確認コメント修正のため。

**Comment by snkw-works** [comment]
@Ken-Nakayama さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、前回お伝えした点について修正が確認できませんでした。
**マージやデプロイ忘れの可能性もございます。** 今一度ご確認をお願いします！

[修正依頼箇所]
#### ユーザー管理機能
- [x] **新規登録・ログイン共にエラーハンドリングができていること（入力に問題がある状態で「会員登録」または「ログイン」ボタンが押された場合、情報は受け入れられず、各ページでエラーメッセージが表示されることを確認）**
新規登録ページでエラーメッセージが表示されません。

#### 商品出品機能
- [x] **入力された販売価格によって、販売手数料や販売利益が変わること(JavaScriptを使用して実装すること)**
一度出品に失敗しエラーが出た後に再度価格を入力すると、販売手数料と販売利益が表示されなくなってしまいます。どの段階でも入力したら表示されるよう修正しましょう。

- [x] **商品出品画面にてエラーハンドリングができていること（入力に問題がある状態で「出品する」ボタンが押された場合、情報は保存されず、出品ページに戻りエラーメッセージが表示されること）**
全ての入力に問題がある状態で「出品する」ボタンを押しても、エラーメッセージが「Image を選択してください
」しか表示されません。

#### 商品詳細機能
- [x] **商品詳細ページにて、商品出品時に登録した情報（商品名・商品画像・販売価格・配送料負担・商品説明・出品者名・カテゴリー・商品の状態・発送元の地域・発送日の目安・○○をもっと見る）が、見本アプリと同様の形で出力されること**
出品者名が、本人情報のお名前で表示されています。ニックネームが表示されるよう修正しましょう。

修正が完了しましたら、一度ご自身の本番環境で正しく動作しているか確認してみましょう！
修正内容が反映されていることを確認できましたら、以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by Ken-Nakayama** [comment]
What
・ユーザー新規登録ページでのエラーメッセージの表示。
・商品手数料等計算用javascriptのrender時読み込み機能の追加。
・商品出品ページでのエラーメッセージの表示修正。
・商品詳細ページでのニックネーム表示。
・renderへのdeployエラーの解消

Why
・フリマアプリ挙動確認コメント修正のため。

**Comment by Ken-Nakayama** [comment]
# Reference
上記コメント修正後、renderへのdeployエラーが発生したため、
renderデータベースのリセットを実施しております。
出品者情報と購入者情報は、再度同じものを登録しております。

**Comment by motomuun** [comment]
@Ken-Nakayama さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、前回依頼した点に関してはすべて修正が完了しておりました！
別の箇所で一点、修正箇所がございましたので以下のご確認をお願い致します。

[修正依頼箇所]
**商品出品機能の確認**

- [x] **販売手数料と販売利益は、小数点以下を切り捨てて表示すること**
販売手数料と販売利益の計算式をご確認ください。以下画像の場合、利益は500円になるかと思います。
<img width="675" alt="スクリーンショット 2024-02-05 9 21 23" src="https://github.com/Ken-Nakayama/furima-39754/assets/65059944/4e7cd3ed-d142-44f5-8bb5-7f03d48b05fe">



修正が完了しましたら、一度ご自身の本番環境で正しく動作しているか確認してみましょう。
修正内容が反映されていることが確認できましたら、再度以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by Ken-Nakayama** [comment]
# What
・販売手数料等計算用javascript計算式の修正

# Why
・フリマアプリ挙動確認コメント修正のため。

**Comment by snkw-works** [comment]
@Ken-Nakayama さん、修正とご提出ありがとうございます‼︎
正常に動作することが確認できました！ **LGTM** です✨　
おめでとうございます🎉
着実に技術力が身につき、実用的なアプリになってきてますね（^^）

**※確認したのは必須機能のみです。追加実装した機能については確認しておりません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるか、再度ご自身でご確認をお願い致します。**
**※Github上の最終課題の履歴はここまで頑張ってきた証です。削除せず大切に保管するようにしましょう。**

![lgtm_01](https://user-images.githubusercontent.com/54050089/186354234-2de2a3d1-500d-4164-81d5-7585cdd03227.png)
